import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--tamanho_fonte', default=16, type=int)
parser.add_argument('--quantidade_imagens', default=10, type=int)
parser.add_argument('--caminho', default="./Data", type=str)
parser.add_argument('--pasta', default="./Treinar", type=str)

argumentos = parser.parse_args()

fontes = {1:  'aldhabi.ttf',
          2:  'aparaj.ttf',
          3:  'aparajb.ttf',
          4:  'aparajbi.ttf',
          5:  'aparaji.ttf',
          6:  'arabtype.ttf',
          7:  'arialuni.ttf',
          8:  'ariblk.ttf',
          9:  'calibril.ttf',
          10: 'calibrili.ttf',
          11: 'comici.ttf',
          12: 'comicz.ttf',
          13: 'Gabriola.ttf',
          14: 'gadugi.ttf',
          15: 'gadugi-bold.ttf',
          16: 'georgiab.ttf',
          17: 'georgiai.ttf',
          18: 'georgiaz.ttf',
          19: 'impact.ttf',
          20: 'kokila.ttf',
          21: 'kokilab.ttf',
          22: 'kokilabi.ttf',
          23: 'kokilai.ttf',
          24: 'leelawad.ttf',
          25: 'majalla.ttf',
          26: 'majallab.ttf',
          27: 'mmrtext.ttf',
          28: 'Nirmala.ttf',
          29: 'palab.ttf',
          30: 'palabi.ttf',
          31: 'palai.ttf',
          32: 'segoeuisl.ttf',
          33: 'Shonar.ttf',
          34: 'Shonarb.ttf',
          35: 'simpbdo.ttf',
          36: 'simpo.ttf',
          37: 'taileb.ttf',
          38: 'tradbdo.ttf',
          39: 'trado.ttf',
          40: 'trebuc.ttf',
          41: 'trebucbd.ttf',
          42: 'trebucbi.ttf',
          43: 'trebucit.ttf',
          44: 'UrdType.ttf',
          45: 'utsaah.ttf',
          46: 'utsaahb.ttf',
          47: 'utsaahbi.ttf',
          48: 'utsaahi.ttf',
          49: 'Vani.ttf',
          50: 'Vanib.ttf',
          51: 'verdana.ttf',
          52: 'verdanab.ttf',
          53: 'verdanai.ttf',
          54: 'verdanaz.ttf',
          55: 'vijaya.ttf'}